<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ringing.aspx.cs" Inherits="WebApplication2.Ringing" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>    body {      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;      display: flex;      justify-content: center;      align-items: center;      height: 100vh;      margin: 0;      background-color: #f5f5f5;    }        .card {      background-color: white;      border-radius: 12px;      box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);      width: 300px;      padding: 20px;      text-align: center;      position: relative;    }        .phone-icon {      width: 60px;      height: 60px;      margin: 0 auto 15px;      position: relative;    }        .phone {      fill: #4CAF50;    }        @keyframes ring {      0%, 100% {        transform: rotate(-10deg);      }      50% {        transform: rotate(10deg);      }    }        .ringing .phone {      animation: ring 0.5s infinite;      transform-origin: center 70%;    }        .waves {      position: absolute;      top: 0;      left: 0;      right: 0;      bottom: 0;    }        .wave {      position: absolute;      top: 50%;      left: 50%;      transform: translate(-50%, -50%);      border: 2px solid rgba(76, 175, 80, 0.4);      border-radius: 50%;      opacity: 0;    }        @keyframes wave {      0% {        width: 10px;        height: 10px;        opacity: 0.8;      }      100% {        width: 80px;        height: 80px;        opacity: 0;      }    }        .wave:nth-child(1) {      animation: wave 2s infinite;    }        .wave:nth-child(2) {      animation: wave 2s infinite 0.5s;    }        .wave:nth-child(3) {      animation: wave 2s infinite 1s;    }        .number {      font-size: 24px;      font-weight: 600;      color: #333;      margin-bottom: 10px;    }        .status {      color: #4CAF50;      font-weight: 500;      margin-bottom: 20px;    }        .buttons {      display: flex;      justify-content: space-between;      margin-top: 20px;    }        .btn {      border: none;      padding: 10px 0;      width: 48%;      border-radius: 8px;      font-weight: 500;      cursor: pointer;      transition: background-color 0.2s;    }        .answer {      background-color: #4CAF50;      color: white;    }        .answer:hover {      background-color: #3e8e41;    }        .decline {      background-color: #f44336;      color: white;    }        .decline:hover {      background-color: #d32f2f;    }  </style>
</head>
<body>  <div class="card">    <div class="phone-icon ringing">      <svg class="phone" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">        <path d="M20.01 15.38c-1.23 0-2.42-.2-3.53-.56-.35-.12-.74-.03-1.01.24l-1.57 1.97c-2.83-1.35-5.48-3.9-6.89-6.83l1.95-1.66c.27-.28.35-.67.24-1.02-.37-1.11-.56-2.3-.56-3.53 0-.54-.45-.99-.99-.99H4.19C3.65 3 3 3.24 3 3.99 3 13.28 10.73 21 20.01 21c.71 0 .99-.63.99-1.18v-3.45c0-.54-.45-.99-.99-.99z"/>      </svg>      <div class="waves">        <div class="wave"></div>        <div class="wave"></div>        <div class="wave"></div>      </div>    </div>      <div class="status"> calling...</div>    <div class="number">(555) 123-4567</div>        <div class="buttons">    <!--  <button class="btn answer">Answer</button> -->      <button class="btn decline">Decline</button>    </div>  </div>
    </form>
</body>
</html>
